env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ .Version }}-next"

#gomod:
#  proxy: true

report_sizes: true

builds:
  - id: secret-tunnel-client
    binary: secret-tunnel-client
    main: ./cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "github.com/starudream/go-lib/constant.VERSION=v{{ .Version }}"
      - -X "github.com/starudream/go-lib/constant.BIDTIME={{ .Date }}"
      - -X "github.com/starudream/go-lib/constant.NAME=secret-tunnel"
      - -X "github.com/starudream/go-lib/constant.PREFIX=ST"
  - id: secret-tunnel-server
    binary: secret-tunnel-server
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "github.com/starudream/go-lib/constant.VERSION=v{{ .Version }}"
      - -X "github.com/starudream/go-lib/constant.BIDTIME={{ .Date }}"
      - -X "github.com/starudream/go-lib/constant.NAME="
      - -X "github.com/starudream/go-lib/constant.PREFIX=ST"

archives:
  - id: secret-tunnel-client
    builds:
      - secret-tunnel-client
    format: tar.gz
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
  - id: secret-tunnel-server
    builds:
      - secret-tunnel-server
    format: tar.gz
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: Performance Improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 30
    - title: Styles
      regexp: "^.*style[(\\w)]*:+.*$"
      order: 50
    - title: Miscellaneous Chores
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 60
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 80
    - title: Dependencies
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 85
    - title: Build System
      regexp: "^.*build[(\\w)]*:+.*$"
      order: 90
    - title: Continuous Integration
      regexp: "^.*ci[(\\w)]*:+.*$"
      order: 95
    - title: Others
      order: 99
