env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  name_template: "{{ .Version }}-next"

report_sizes: true

builds:
  - id: secret-tunnel-client
    binary: secret-tunnel-client
    main: ./cmd/client
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "github.com/starudream/go-lib/constant.VERSION=v{{ .Version }}"
      - -X "github.com/starudream/go-lib/constant.BIDTIME={{ .Date }}"
      - -X "github.com/starudream/go-lib/constant.NAME=secret-tunnel"
      - -X "github.com/starudream/go-lib/constant.PREFIX=ST"
  - id: secret-tunnel-server
    binary: secret-tunnel-server
    main: ./cmd/server
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X "github.com/starudream/go-lib/constant.VERSION=v{{ .Version }}"
      - -X "github.com/starudream/go-lib/constant.BIDTIME={{ .Date }}"
      - -X "github.com/starudream/go-lib/constant.NAME=secret-tunnel"
      - -X "github.com/starudream/go-lib/constant.PREFIX=ST"

upx:
  - enabled: true

archives:
  - id: secret-tunnel-client
    builds:
      - secret-tunnel-client
    format: tar.gz
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
  - id: secret-tunnel-server
    builds:
      - secret-tunnel-server
    format: tar.gz
    name_template: "{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile-client
    use: buildx
    image_templates:
      - "starudream/secret-tunnel-client:latest-amd64"
      - "starudream/secret-tunnel-client:{{ .Tag }}-amd64"
      - "ghcr.io/starudream/secret-tunnel-client:latest-amd64"
      - "ghcr.io/starudream/secret-tunnel-client:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile-client
    use: buildx
    image_templates:
      - "starudream/secret-tunnel-client:latest-arm64"
      - "starudream/secret-tunnel-client:{{ .Tag }}-arm64"
      - "ghcr.io/starudream/secret-tunnel-client:latest-arm64"
      - "ghcr.io/starudream/secret-tunnel-client:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile-server
    use: buildx
    image_templates:
      - "starudream/secret-tunnel-server:latest-amd64"
      - "starudream/secret-tunnel-server:{{ .Tag }}-amd64"
      - "ghcr.io/starudream/secret-tunnel-server:latest-amd64"
      - "ghcr.io/starudream/secret-tunnel-server:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile-server
    use: buildx
    image_templates:
      - "starudream/secret-tunnel-server:latest-arm64"
      - "starudream/secret-tunnel-server:{{ .Tag }}-arm64"
      - "ghcr.io/starudream/secret-tunnel-server:latest-arm64"
      - "ghcr.io/starudream/secret-tunnel-server:{{ .Tag }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.url={{ .GitURL }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

docker_manifests:
  - name_template: "starudream/secret-tunnel-client:latest"
    image_templates:
      - "starudream/secret-tunnel-client:latest-amd64"
      - "starudream/secret-tunnel-client:latest-arm64"
  - name_template: "starudream/secret-tunnel-client:{{ .Tag }}"
    image_templates:
      - "starudream/secret-tunnel-client:{{ .Tag }}-amd64"
      - "starudream/secret-tunnel-client:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/starudream/secret-tunnel-client:latest"
    image_templates:
      - "ghcr.io/starudream/secret-tunnel-client:latest-amd64"
      - "ghcr.io/starudream/secret-tunnel-client:latest-arm64"
  - name_template: "ghcr.io/starudream/secret-tunnel-client:{{ .Tag }}"
    image_templates:
      - "ghcr.io/starudream/secret-tunnel-client:{{ .Tag }}-amd64"
      - "ghcr.io/starudream/secret-tunnel-client:{{ .Tag }}-arm64"

  - name_template: "starudream/secret-tunnel-server:latest"
    image_templates:
      - "starudream/secret-tunnel-server:latest-amd64"
      - "starudream/secret-tunnel-server:latest-arm64"
  - name_template: "starudream/secret-tunnel-server:{{ .Tag }}"
    image_templates:
      - "starudream/secret-tunnel-server:{{ .Tag }}-amd64"
      - "starudream/secret-tunnel-server:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/starudream/secret-tunnel-server:latest"
    image_templates:
      - "ghcr.io/starudream/secret-tunnel-server:latest-amd64"
      - "ghcr.io/starudream/secret-tunnel-server:latest-arm64"
  - name_template: "ghcr.io/starudream/secret-tunnel-server:{{ .Tag }}"
    image_templates:
      - "ghcr.io/starudream/secret-tunnel-server:{{ .Tag }}-amd64"
      - "ghcr.io/starudream/secret-tunnel-server:{{ .Tag }}-arm64"

checksum:
  name_template: "checksums.txt"

release:
  draft: true
  replace_existing_draft: true
  target_commitish: "{{ .Commit }}"

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 10
    - title: Bug Fixes
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 20
    - title: Performance Improvements
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 30
    - title: Styles
      regexp: "^.*style[(\\w)]*:+.*$"
      order: 50
    - title: Miscellaneous Chores
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 60
    - title: Documentation
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 80
    - title: Dependencies
      regexp: "^.*deps[(\\w)]*:+.*$"
      order: 85
    - title: Build System
      regexp: "^.*build[(\\w)]*:+.*$"
      order: 90
    - title: Continuous Integration
      regexp: "^.*ci[(\\w)]*:+.*$"
      order: 95
    - title: Others
      order: 99
