FROM starudream/golang AS builder

WORKDIR /build

COPY . .

RUN make clean && make bin-server && make upx

FROM starudream/alpine-glibc:latest

WORKDIR /

COPY --from=builder /build/bin/sts /server

CMD /server
