name: Golang

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - CHANGELOG.md

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: stable
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: build --clean --snapshot
